// CI  for when a commit to master
//  
pipeline {
    agent any

    stages {
        stage('Code Checkout') {
            steps {
                echo 'Checkout..'
                git branch: 'master', url:'https://github.com/M25790353/NewsAPI.git'
            }
        }
        stage('Build') {
            steps {
                echo '!!!!! Building..'
                git url:'https://github.com/M25790353/NewsAPI.git'
                withMaven (
                    maven: 'my-maven'
                ){

                    sh "mvn clean verify"
                }
            
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}